"""Stage 2 tests-first witnesses for the canonical session-availability model.

Written BEFORE `mnq_lab/spine/availability.py` exists (D32 repair, Stage 2).
Every test therefore fails at import until Stage 3 implements the module, so the
whole module is marked ``xfail(strict=True)``: when the implementation lands the
strict marker turns these into failures and forces the marker's removal. A
skipped test would be a check that cannot fail, which this project forbids.

Expected values are literal and derived by hand from the declared boundary
convention. None is generated by calling the implementation.

Time is expressed in America/Chicago minutes from midnight:
    08:30 -> 510      11:56 -> 716      15:00 -> 900
    12:00 -> 720      14:00 -> 840

NOTE ON THE FOUR MARCH 2020 SESSIONS. Authoritative CME futures interruption
boundaries are NOT established (design doc section 10). No test here registers an
interruption on 20200309/0312/0316/0318. Interruption behaviour is pinned on a
clearly synthetic session id (29990101) so that nothing in this file can be
mistaken for a registered historical fact.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.xfail(
    strict=True,
    reason="Stage 3 implements mnq_lab/spine/availability.py; Stage 3 removes this marker",
)

CT = "America/Chicago"
SOURCE = "SYNTHETIC-TEST-NOT-A-REGISTERED-SOURCE"

RTH_OPEN = 510
RTH_CLOSE_FULL = 900
EARLY_CLOSE = 720

FULL_SESSION = 20200102
EARLY_SESSION = 20191129
NO_RTH_SESSION = 20210402
INTERRUPTED_SESSION = 29990101
UNKNOWN_SESSION = 29990102

TRUNCATION_SESSIONS = (20200228, 20200630)
MARCH_SESSIONS = (20200309, 20200312, 20200316, 20200318)


def _mod():
    """Import inside the test so collection succeeds before Stage 3."""
    from mnq_lab.spine import availability

    return availability


def _schedule(mod, session_id, *, status="full_rth", close=RTH_CLOSE_FULL,
              open_ct=RTH_OPEN, interruptions=(), timezone=CT):
    return mod.SessionSchedule(
        session_id=session_id,
        scheduled_rth_open_ct=open_ct,
        scheduled_rth_close_ct=close,
        scheduled_rth_status=status,
        structural_interruptions=tuple(interruptions),
        timezone=timezone,
        calendar_version="mnq-cme-equity-index-calendar-v1",
        calendar_sha256="b86e112c16112bf11a6a548ca8b3f21d28a08f90442b4dde84098f9d3f6eb069",
        interruption_source_id=None,
    )


def _interruption(mod, start, end, source=SOURCE):
    return mod.StructuralInterruption(
        start_ct_minute=start,
        end_ct_minute=end,
        reason="registered_interruption",
        source_id=source,
    )


def _table(mod, *schedules, exclusions=()):
    return mod.build_session_schedule_table(schedules, exclusions=exclusions)


def _decide(mod, table, session_id, tau, horizon):
    return mod.outcome_window_structurally_available(
        session_id=session_id,
        tau_ct_minute=tau,
        horizon_minutes=horizon,
        schedule_table=table,
    )


# --------------------------------------------------------------------------
# 1-4, 10-12: schedule-driven availability
# --------------------------------------------------------------------------


def test_1_ordinary_full_rth_reproduces_the_old_boundary_exactly():
    mod = _mod()
    table = _table(mod, _schedule(mod, FULL_SESSION))
    # 14:00 + 60 == 15:00 -> fits under the v1 rule tau + delta <= rth_end
    assert _decide(mod, table, FULL_SESSION, 840, 60).available is True
    # 14:05 + 60 == 15:05 -> does not fit
    d = _decide(mod, table, FULL_SESSION, 845, 60)
    assert d.available is False
    assert d.reason == "scheduled_close"
    assert _decide(mod, table, FULL_SESSION, 510, 15).available is True


def test_2_scheduled_early_close_makes_a_crossing_window_unavailable():
    mod = _mod()
    table = _table(mod, _schedule(mod, EARLY_SESSION, status="shortened_rth",
                                  close=EARLY_CLOSE))
    d = _decide(mod, table, EARLY_SESSION, 840, 15)  # 14:00 on a 12:00 close
    assert d.available is False
    assert d.reason == "scheduled_close"


def test_3_exact_close_boundary_is_available_on_both_full_and_short_sessions():
    """Declared convention: tau + delta <= close, equality AVAILABLE."""
    mod = _mod()
    table = _table(
        mod,
        _schedule(mod, FULL_SESSION),
        _schedule(mod, EARLY_SESSION, status="shortened_rth", close=EARLY_CLOSE),
    )
    assert _decide(mod, table, FULL_SESSION, 840, 60).available is True   # 900 == 900
    assert _decide(mod, table, EARLY_SESSION, 690, 30).available is True  # 720 == 720
    assert _decide(mod, table, EARLY_SESSION, 695, 30).available is False  # 725 > 720


def test_4_no_scheduled_rth_makes_every_window_unavailable():
    mod = _mod()
    table = _table(mod, _schedule(mod, NO_RTH_SESSION, status="no_scheduled_rth",
                                  open_ct=None, close=None))
    for tau in (510, 600, 840):
        for horizon in (15, 30, 60):
            d = _decide(mod, table, NO_RTH_SESSION, tau, horizon)
            assert d.available is False
            assert d.reason == "no_scheduled_rth"


def test_10_absent_bars_do_not_change_structural_availability():
    """Availability is a function of the schedule alone; bars are not an input."""
    mod = _mod()
    table = _table(mod, _schedule(mod, FULL_SESSION))
    assert _decide(mod, table, FULL_SESSION, 600, 60).available is True
    import inspect

    params = set(
        inspect.signature(mod.outcome_window_structurally_available).parameters
    )
    assert not params & {"bars", "n_present_bars", "observed", "store"}


def test_11_the_two_unresolved_truncations_are_not_structural_closures():
    mod = _mod()
    table = _table(mod, *(_schedule(mod, s) for s in TRUNCATION_SESSIONS))
    for session in TRUNCATION_SESSIONS:
        assert table.lookup(session).scheduled_rth_status == "full_rth"
        assert table.lookup(session).structural_interruptions == ()
        # 10:00 and 09:15 observed ends must NOT become scheduled closes
        assert _decide(mod, table, session, 660, 60).available is True


def test_12_march_sessions_are_excluded_whole_not_intraday_classified():
    """D33: boundaries unresolved, so the whole session leaves the population.

    Superseded the earlier expectation that these sessions stayed available. They
    are NOT given an interruption, NOT retyped as truncated, and NOT treated as
    ordinary missing data -- they are excluded, and no anchor survives.
    """
    mod = _mod()
    from mnq_lab import SpineError

    table = _table(
        mod,
        *(_schedule(mod, s) for s in MARCH_SESSIONS),
        exclusions=tuple(
            mod.SessionExclusion(
                session_id=s,
                reason="excluded_unresolved_official_interruption",
                source_id="D33",
                recorded_by_ruling="D33",
            )
            for s in MARCH_SESSIONS
        ),
    )
    for session in MARCH_SESSIONS:
        assert table.is_excluded(session) is True
        # no interruption is invented for them
        assert table.lookup(session).structural_interruptions == ()
        # and no window may be evaluated: excluded sessions fail closed
        for tau, horizon in ((510, 15), (600, 60), (840, 60)):
            with pytest.raises(SpineError):
                _decide(mod, table, session, tau, horizon)


def test_12b_exclusion_is_checked_before_window_availability():
    """An excluded session must never reach the scheduled-close arithmetic."""
    mod = _mod()
    from mnq_lab import SpineError

    excluded = 20200309
    table = _table(
        mod,
        _schedule(mod, excluded),
        exclusions=(mod.SessionExclusion(
            session_id=excluded,
            reason="excluded_unresolved_official_interruption",
            source_id="D33",
            recorded_by_ruling="D33",
        ),),
    )
    # 845+60 would be a scheduled_close failure on a non-excluded session;
    # here it must fail closed on exclusion instead, not return a reason.
    with pytest.raises(SpineError):
        _decide(mod, table, excluded, 845, 60)


def test_12c_unknown_exclusion_reason_and_duplicates_fail_closed():
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):
        mod.SessionExclusion(session_id=20200309, reason="because_it_looked_odd",
                             source_id="D33", recorded_by_ruling="D33")
    dup = mod.SessionExclusion(
        session_id=20200309, reason="excluded_unresolved_official_interruption",
        source_id="D33", recorded_by_ruling="D33")
    with pytest.raises(SpineError):
        _table(mod, _schedule(mod, 20200309), exclusions=(dup, dup))


def test_12d_the_two_unresolved_truncations_are_not_excluded():
    """D33 covers the four March sessions ONLY. 20200228 and 20200630 stay in."""
    mod = _mod()
    table = _table(mod, *(_schedule(mod, s) for s in TRUNCATION_SESSIONS))
    for session in TRUNCATION_SESSIONS:
        assert table.is_excluded(session) is False
        assert _decide(mod, table, session, 660, 60).available is True


# --------------------------------------------------------------------------
# 5-9: interruption geometry, half-open [start, end)
# --------------------------------------------------------------------------


def _interrupted(mod):
    return _table(
        mod,
        _schedule(mod, INTERRUPTED_SESSION,
                  interruptions=(_interruption(mod, 700, 715),)),
    )


def test_5_window_spanning_an_interruption_is_unavailable():
    mod = _mod()
    d = _decide(mod, _interrupted(mod), INTERRUPTED_SESSION, 695, 15)  # [695,710)
    assert d.available is False
    assert d.reason == "registered_interruption"


def test_6_window_ending_exactly_at_interruption_start_is_available():
    mod = _mod()
    # [685, 700) touches but does not intersect [700, 715)
    assert _decide(mod, _interrupted(mod), INTERRUPTED_SESSION, 685, 15).available is True


def test_7_window_beginning_exactly_at_interruption_end_is_available():
    mod = _mod()
    # [715, 730) touches but does not intersect [700, 715)
    assert _decide(mod, _interrupted(mod), INTERRUPTED_SESSION, 715, 15).available is True


def test_8_post_resumption_window_survives():
    mod = _mod()
    assert _decide(mod, _interrupted(mod), INTERRUPTED_SESSION, 800, 60).available is True


def test_9_pre_interruption_window_survives():
    mod = _mod()
    assert _decide(mod, _interrupted(mod), INTERRUPTED_SESSION, 600, 15).available is True


# --------------------------------------------------------------------------
# 16-22: fail-closed contract
# --------------------------------------------------------------------------


def test_16_unknown_session_fails_closed():
    mod = _mod()
    from mnq_lab import SpineError

    table = _table(mod, _schedule(mod, FULL_SESSION))
    with pytest.raises(SpineError):
        _decide(mod, table, UNKNOWN_SESSION, 600, 15)
    with pytest.raises(SpineError):
        table.lookup(UNKNOWN_SESSION)


def test_17_reversed_interruption_fails_closed():
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):
        _interruption(mod, 715, 700)
    with pytest.raises(SpineError):
        _interruption(mod, 700, 700)  # empty is also rejected


def test_18_overlapping_interruptions_fail_closed():
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):
        _schedule(mod, INTERRUPTED_SESSION, interruptions=(
            _interruption(mod, 700, 720),
            _interruption(mod, 710, 730),
        ))


def test_19_interruption_outside_the_scheduled_session_fails_closed():
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):  # starts before the open
        _schedule(mod, INTERRUPTED_SESSION,
                  interruptions=(_interruption(mod, 480, 520),))
    with pytest.raises(SpineError):  # ends after the close
        _schedule(mod, INTERRUPTED_SESSION,
                  interruptions=(_interruption(mod, 880, 960),))


def test_20_wrong_timezone_fails_closed():
    mod = _mod()
    from mnq_lab import SpineError

    for bad in ("UTC", "America/New_York", "US/Central", ""):
        with pytest.raises(SpineError):
            _schedule(mod, FULL_SESSION, timezone=bad)


def test_21_duplicate_session_schedule_fails_closed():
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):
        _table(mod, _schedule(mod, FULL_SESSION), _schedule(mod, FULL_SESSION))


def test_22_noncanonical_interruption_ordering_fails_closed():
    """Declared rule: strictly ascending by start_ct_minute. No silent sort."""
    mod = _mod()
    from mnq_lab import SpineError

    with pytest.raises(SpineError):
        _schedule(mod, INTERRUPTED_SESSION, interruptions=(
            _interruption(mod, 800, 815),
            _interruption(mod, 700, 715),
        ))


def test_undeclared_horizon_and_status_fail_closed():
    mod = _mod()
    from mnq_lab import SpineError

    table = _table(mod, _schedule(mod, FULL_SESSION))
    with pytest.raises(SpineError):
        _decide(mod, table, FULL_SESSION, 600, 45)
    with pytest.raises(SpineError):
        _schedule(mod, FULL_SESSION, status="half_day")


def test_reason_is_not_applicable_exactly_when_available():
    mod = _mod()
    table = _table(
        mod,
        _schedule(mod, FULL_SESSION),
        _schedule(mod, EARLY_SESSION, status="shortened_rth", close=EARLY_CLOSE),
    )
    for session, tau, horizon in (
        (FULL_SESSION, 600, 15), (FULL_SESSION, 845, 60),
        (EARLY_SESSION, 690, 30), (EARLY_SESSION, 840, 15),
    ):
        d = _decide(mod, table, session, tau, horizon)
        assert (d.reason == "not_applicable") is d.available
        assert d.reason in mod.UNAVAILABILITY_REASONS


# --------------------------------------------------------------------------
# 13-15: named mutants. Each must DISAGREE with the canonical answer on its
# witness, proving the witness discriminates rather than merely passing.
# --------------------------------------------------------------------------


def _mutant_fixed_1500(session_id, tau, horizon, table):
    """Mutant 13: ignores the schedule, uses a fixed 15:00 close."""
    return tau + horizon <= RTH_CLOSE_FULL


def _mutant_infer_close_from_last_bar(session_id, tau, horizon, observed_last_end):
    """Mutant 14: derives the close from observed bars instead of the schedule."""
    return tau + horizon <= observed_last_end


def _mutant_exclude_whole_session(session_id, tau, horizon, table):
    """Mutant 15: excludes the entire session when any interruption exists."""
    return not table.lookup(session_id).structural_interruptions


def test_13_fixed_1500_mutant_fails_the_early_close_witness():
    mod = _mod()
    table = _table(mod, _schedule(mod, EARLY_SESSION, status="shortened_rth",
                                  close=EARLY_CLOSE))
    canonical = _decide(mod, table, EARLY_SESSION, 840, 15).available
    assert canonical is False
    assert _mutant_fixed_1500(EARLY_SESSION, 840, 15, table) is True
    assert canonical != _mutant_fixed_1500(EARLY_SESSION, 840, 15, table)


def test_14_missing_bar_inference_mutant_fails_on_an_unresolved_truncation():
    mod = _mod()
    table = _table(mod, _schedule(mod, 20200228))
    # 20200228 is a REGULAR full_rth session whose observed bars stop at 10:00.
    canonical = _decide(mod, table, 20200228, 660, 60).available
    assert canonical is True
    inferred = _mutant_infer_close_from_last_bar(20200228, 660, 60, 600)
    assert inferred is False
    assert canonical != inferred


def test_15_whole_session_exclusion_mutant_kills_a_valid_post_resumption_window():
    mod = _mod()
    table = _interrupted(mod)
    canonical = _decide(mod, table, INTERRUPTED_SESSION, 800, 60).available
    assert canonical is True
    assert _mutant_exclude_whole_session(INTERRUPTED_SESSION, 800, 60, table) is False
    assert canonical != _mutant_exclude_whole_session(
        INTERRUPTED_SESSION, 800, 60, table
    )
