"""Synthetic-only Phase 8 contrast and estimand primitives."""

from mnq_lab.phase8.contrasts import (
    CONTRAST_NAMES,
    OUTCOME_NAMES,
    SESSION_PHASES,
    STATISTICS,
    VOLATILITY_STATES,
    CellKey,
    contrast_support,
    degenerate_baseline,
    statistic_probability,
    support_masks,
    tick_contrast,
    weighted_quantile_ticks,
)
from mnq_lab.phase8.estimands import ESTIMAND_NAMES, build_estimand_weights
from mnq_lab.phase8.diagnostics import (
    STATUS_PRECEDENCE,
    anchor_support_failure,
    completion_diagnostics,
    positivity_diagnostics,
    status_decision,
)
from mnq_lab.phase8.day_types import (
    DAY_TYPES,
    classify_calendar_day_type,
    declared_day_type_rows,
    evaluate_day_type_distribution,
)
from mnq_lab.phase8.inventory import declared_result_rows
from mnq_lab.phase8.interactions import (
    DESCRIPTIVE_ONLY_LABEL,
    INTERACTION_POPULATION_ESTIMAND,
    INTERACTION_STATISTICS,
    INTERACTION_SUPPORT_KIND,
    REFERENCE_CELL,
    assemble_interaction_rows,
    build_four_cell_support,
    declared_interaction_rows,
    evaluate_interaction,
    interaction_bootstrap_inputs,
    interaction_cells,
)
from mnq_lab.phase8.uncertainty import (
    BootstrapInteractionRequest,
    BootstrapIntervalRequest,
    BootstrapQuantileTerm,
    bootstrap_contract,
    joint_bootstrap_intervals,
)
from mnq_lab.phase8.runner import RunnerOperatingConfig, run_phase8

__all__ = [
    "CONTRAST_NAMES",
    "DAY_TYPES",
    "ESTIMAND_NAMES",
    "OUTCOME_NAMES",
    "SESSION_PHASES",
    "STATISTICS",
    "STATUS_PRECEDENCE",
    "VOLATILITY_STATES",
    "CellKey",
    "BootstrapInteractionRequest",
    "BootstrapIntervalRequest",
    "BootstrapQuantileTerm",
    "build_estimand_weights",
    "build_four_cell_support",
    "bootstrap_contract",
    "anchor_support_failure",
    "completion_diagnostics",
    "classify_calendar_day_type",
    "contrast_support",
    "degenerate_baseline",
    "declared_result_rows",
    "declared_day_type_rows",
    "declared_interaction_rows",
    "DESCRIPTIVE_ONLY_LABEL",
    "INTERACTION_STATISTICS",
    "INTERACTION_SUPPORT_KIND",
    "INTERACTION_POPULATION_ESTIMAND",
    "REFERENCE_CELL",
    "assemble_interaction_rows",
    "evaluate_interaction",
    "evaluate_day_type_distribution",
    "interaction_bootstrap_inputs",
    "interaction_cells",
    "positivity_diagnostics",
    "joint_bootstrap_intervals",
    "statistic_probability",
    "support_masks",
    "status_decision",
    "tick_contrast",
    "weighted_quantile_ticks",
    "RunnerOperatingConfig",
    "run_phase8",
]
